name: Build and Deploy (FTP)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VUE_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.VUE_APP_EMAILJS_PUBLIC_KEY }}
          VUE_APP_EMAILJS_SERVICE_ID: ${{ secrets.VUE_APP_EMAILJS_SERVICE_ID }}
          VUE_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.VUE_APP_EMAILJS_TEMPLATE_ID }}
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: ${{ endsWith(secrets.FTP_SERVER_DIR, '/') && secrets.FTP_SERVER_DIR || format('{0}/', secrets.FTP_SERVER_DIR) }}
          local-dir: dist/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.DS_Store
