name: Smoke

on:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo
        run: |
          echo "Runner OK"
          node --version || true
          npm --version || true
